name: NewVote
version: ${project.version}
main: net.kunmc.lab.newvote.NewVote
description: Voting plugin with tab-list status visualization.
authors:
  - Yanaaaaa
  - Cyrne1_7208
api-version: 1.15
commands:
  v:
    permission: newvote.v
  yvote:
    permission: newvote.v
  vs:
    permission: newvote.vs
  vget:
    permission: newvote.vs
permissions:
  newvote.v:
    default: true
  newvote.vs:
    default: op
